//! # Zod Schema Generation for Rust Types
//!
//! Generate [Zod](https://zod.dev) schemas and TypeScript types from Rust types with full serde rename support.
//!
//! ## Quick Start with Derive Macro (Recommended)
//!
//! ```rust,ignore
//! use zod_gen::{ZodSchema, ZodGenerator};
//! use zod_gen_derive::ZodSchema;
//! use serde::{Serialize, Deserialize};
//!
//! #[derive(ZodSchema, Serialize, Deserialize)]
//! struct User {
//!     id: u32,
//!     name: String,
//!     email: Option<String>,
//! }
//!
//! #[derive(ZodSchema, Serialize, Deserialize)]
//! enum Status {
//!     #[serde(rename = "active")]
//!     Active,
//!     #[serde(rename = "inactive")]
//!     Inactive,
//! }
//!
//! let mut generator = ZodGenerator::new();
//! generator.add_schema::<User>("User");
//! generator.add_schema::<Status>("Status");
//!
//! let typescript = generator.generate();
//! // typescript contains the generated Zod schemas
//! ```
//!
//! This generates:
//!
//! ```typescript
//! // Automatically generated by zod_gen
//! import * as z from 'zod';
//!
//! export const UserSchema = z.object({
//!   id: z.number(),
//!   name: z.string(),
//!   email: z.string().nullable()
//! });
//! export type User = z.infer<typeof UserSchema>;
//!
//! export const StatusSchema = z.union([z.literal("active"), z.literal("inactive")]);
//! export type Status = z.infer<typeof StatusSchema>;
//! ```
//!
//! ## Manual Implementation
//!
//! For custom schema generation, implement the `ZodSchema` trait manually:
//!
//! ```rust
//! use zod_gen::{ZodSchema, zod_object, zod_string};
//!
//! struct CustomType {
//!     field: String,
//! }
//!
//! impl ZodSchema for CustomType {
//!     fn zod_schema() -> String {
//!         zod_object(&[("field", zod_string())])
//!     }
//! }
//! ```
//!
//! ## Features
//!
//! - **Derive Macro**: Automatic schema generation with `#[derive(ZodSchema)]`
//! - **Serde Rename Support**: Full support for `#[serde(rename = "...")]` attributes
//! - **Type Safety**: Generated TypeScript types match your Rust types exactly
//! - **Generic Types**: Built-in support for `Option<T>`, `Vec<T>`, `HashMap<String, T>`
//! - **Batch Generation**: Generate multiple schemas in a single TypeScript file
//!
//! ## Installation
//!
//! Add both crates to your `Cargo.toml`:
//!
//! ```toml
//! [dependencies]
//! zod_gen = "1.1.7"
//! zod_gen_derive = "1.1.7"
//! serde = { version = "1.0", features = ["derive"] }
//! ```

use std::{
    cmp::Reverse,
    collections::{BinaryHeap, HashMap, HashSet},
    fmt::Write,
};

/// Trait for Rust types that can produce a Zod schema
pub trait ZodSchema {
    /// Returns the Zod schema as a string
    fn zod_schema() -> String;
}

/// Helper functions for building Zod schema strings
pub fn zod_string() -> &'static str {
    "z.string()"
}
pub fn zod_number() -> &'static str {
    "z.number()"
}
pub fn zod_bigint() -> &'static str {
    "z.bigint()"
}
pub fn zod_boolean() -> &'static str {
    "z.boolean()"
}

pub fn zod_nullable(inner: &str) -> String {
    format!("{inner}.nullable()")
}
pub fn zod_array(inner: &str) -> String {
    format!("z.array({inner})")
}
pub fn zod_record(value: &str) -> String {
    format!("z.record(z.string(), {value})")
}

fn is_ts_identifier_start(ch: char) -> bool {
    ch == '_' || ch == '$' || ch.is_ascii_alphabetic()
}

fn is_ts_identifier_part(ch: char) -> bool {
    ch == '_' || ch == '$' || ch.is_ascii_alphanumeric()
}

fn is_valid_ts_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(ch) if is_ts_identifier_start(ch) => {
            for ch in chars {
                if !is_ts_identifier_part(ch) {
                    return false;
                }
            }
            true
        }
        _ => false,
    }
}

fn ts_quoted_literal(value: &str, quote: char) -> String {
    let mut escaped = String::with_capacity(value.len() + 2);
    escaped.push(quote);
    for ch in value.chars() {
        match ch {
            '"' if quote == '"' => escaped.push_str("\\\""),
            '\'' if quote == '\'' => escaped.push_str("\\'"),
            '\\' => escaped.push_str("\\\\"),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            '\u{08}' => escaped.push_str("\\b"),
            '\u{0C}' => escaped.push_str("\\f"),
            '\u{2028}' => escaped.push_str("\\u2028"),
            '\u{2029}' => escaped.push_str("\\u2029"),
            ch if ch.is_control() => {
                let _ = write!(escaped, "\\u{:04X}", ch as u32);
            }
            _ => escaped.push(ch),
        }
    }
    escaped.push(quote);
    escaped
}

fn ts_double_quoted_literal(value: &str) -> String {
    ts_quoted_literal(value, '"')
}

fn ts_single_quoted_literal(value: &str) -> String {
    ts_quoted_literal(value, '\'')
}

fn format_ts_property_key(name: &str) -> String {
    if is_valid_ts_identifier(name) {
        name.to_string()
    } else {
        ts_double_quoted_literal(name)
    }
}

fn prev_non_whitespace(s: &str, idx: usize) -> Option<char> {
    s[..idx].chars().rev().find(|c| !c.is_whitespace())
}

fn next_non_whitespace(s: &str, idx: usize) -> Option<char> {
    s[idx..].chars().find(|c| !c.is_whitespace())
}

fn is_valid_reference_context(prev: Option<char>, next: Option<char>) -> bool {
    if prev.is_none() && next.is_none() {
        return false;
    }

    let prev_ok = match prev {
        None => true,
        Some(ch) => matches!(ch, ':' | '(' | '[' | ',' | '='),
    };

    let next_ok = match next {
        None => true,
        Some(ch) => matches!(ch, ')' | ',' | ']' | '}' | '.'),
    };

    prev_ok && next_ok
}

fn replace_schema_refs(schema: String, target: &str, replacement_name: &str) -> (String, bool) {
    if target.is_empty() {
        return (schema, false);
    }

    let replacement = format!("{replacement_name}Schema");
    let source = schema;

    let target_variants = build_target_variants(target, source.as_str());
    if target_variants
        .iter()
        .all(|variant| !source.as_str().contains(variant))
    {
        return (source, false);
    }

    let mut result = String::with_capacity(source.len());
    let mut last = 0usize;
    let mut replaced = false;
    let bytes = source.as_str();

    while last < bytes.len() {
        let mut next_match: Option<(usize, &String)> = None;

        for variant in &target_variants {
            if let Some(rel_pos) = bytes[last..].find(variant) {
                let abs_pos = last + rel_pos;
                let update = match next_match {
                    Some((current_pos, _)) => abs_pos < current_pos,
                    None => true,
                };
                if update {
                    next_match = Some((abs_pos, variant));
                }
            }
        }

        let Some((start, variant)) = next_match else {
            result.push_str(&bytes[last..]);
            break;
        };

        let end = start + variant.len();
        let prev = prev_non_whitespace(bytes, start);
        let next = next_non_whitespace(bytes, end);

        if is_valid_reference_context(prev, next) {
            result.push_str(&bytes[last..start]);
            result.push_str(&replacement);
            last = end;
            replaced = true;
        } else {
            let char_len = bytes[start..]
                .chars()
                .next()
                .map(|ch| ch.len_utf8())
                .unwrap_or(1);
            result.push_str(&bytes[last..start + char_len]);
            last = start + char_len;
        }
    }

    if replaced {
        (result, true)
    } else {
        (source, false)
    }
}

fn build_target_variants(target: &str, search_space: &str) -> Vec<String> {
    use std::collections::HashSet;

    let mut variants = Vec::new();
    variants.push(target.to_string());

    let mut indents: HashSet<String> = HashSet::new();
    if let Some(first_non_ws) = target.chars().find(|c| !c.is_whitespace()) {
        let mut offset = 0usize;
        while let Some(rel_pos) = search_space[offset..].find(first_non_ws) {
            let idx = offset + rel_pos;
            let line_start = search_space[..idx]
                .rfind('\n')
                .map(|pos| pos + 1)
                .unwrap_or(0);
            if line_start < idx {
                let indent_candidate = &search_space[line_start..idx];
                if !indent_candidate.is_empty()
                    && indent_candidate.chars().all(|ch| ch == ' ' || ch == '\t')
                {
                    indents.insert(indent_candidate.to_string());
                }
            }
            offset = idx + first_non_ws.len_utf8();
        }
    }

    for indent in indents {
        let variant = indent_schema_lines(target, &indent);
        if !variant.is_empty() && variant != target {
            variants.push(variant);
        }
    }

    variants
}

fn indent_schema_lines(schema: &str, indent: &str) -> String {
    if indent.is_empty() {
        return schema.to_string();
    }

    let mut result = String::with_capacity(schema.len() + indent.len() * schema.lines().count());
    let mut lines = schema.split('\n');

    if let Some(first) = lines.next() {
        result.push_str(first);
    }

    for line in lines {
        result.push('\n');
        if !line.is_empty() {
            result.push_str(indent);
        }
        result.push_str(line);
    }

    result
}

pub fn zod_object(fields: &[(&str, &str)]) -> String {
    let items: Vec<String> = fields
        .iter()
        .map(|(k, v)| format!("  {}: {v}", format_ts_property_key(k)))
        .collect();
    format!("z.object({{\n{}\n}})", items.join(",\n"))
}

pub fn zod_enum(variants: &[&str]) -> String {
    let lits: Vec<String> = variants
        .iter()
        .map(|v| format!("z.literal({})", ts_single_quoted_literal(v)))
        .collect();
    format!("z.union([{}])", lits.join(", "))
}

/// Generator that collects schemas and writes TypeScript files
///
/// The `ZodGenerator` generates Zod schemas with proper serde rename support
/// from Rust types, providing TypeScript type safety.
pub struct ZodGenerator {
    schemas: Vec<(String, String)>,
}

impl Default for ZodGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl ZodGenerator {
    pub fn new() -> Self {
        Self {
            schemas: Vec::new(),
        }
    }

    /// Add a Zod schema for a Rust type
    pub fn add_schema<T: ZodSchema>(&mut self, name: &str) {
        let schema = T::zod_schema();
        let name = name.to_string();
        if let Some(existing) = self.schemas.iter_mut().find(|(n, _)| *n == name) {
            existing.1 = schema;
        } else {
            self.schemas.push((name, schema));
        }
    }

    /// Generate Zod schemas file
    ///
    /// Creates a TypeScript file with Zod schemas and inferred types.
    pub fn generate(&self) -> String {
        let entries: Vec<(String, String)> = self.schemas.clone();
        let originals = entries.clone();
        let mut schema_occurrences: HashMap<String, usize> = HashMap::new();
        for (_, schema) in &originals {
            *schema_occurrences.entry(schema.clone()).or_insert(0) += 1;
        }

        let mut processed: Vec<(String, String)> = Vec::with_capacity(entries.len());
        let mut processed_map: HashMap<String, String> = HashMap::new();
        let mut dependency_map: HashMap<String, Vec<String>> = HashMap::new();

        for (name, schema) in entries.into_iter() {
            let mut updated = schema;
            let mut deps = Vec::new();
            let mut seen_deps: HashSet<String> = HashSet::new();

            loop {
                let mut iteration_changed = false;

                for (dep_name, dep_schema) in &originals {
                    if dep_name == &name {
                        continue;
                    }
                    if schema_occurrences
                        .get(dep_schema.as_str())
                        .copied()
                        .unwrap_or(0)
                        > 1
                    {
                        continue;
                    }
                    let candidate_schema = processed_map
                        .get(dep_name)
                        .map(|value| value.as_str())
                        .unwrap_or(dep_schema.as_str());

                    let current = std::mem::take(&mut updated);
                    let (new_schema, replaced) =
                        replace_schema_refs(current, candidate_schema, dep_name);
                    if replaced {
                        if seen_deps.insert(dep_name.clone()) {
                            deps.push(dep_name.clone());
                        }
                        iteration_changed = true;
                    }
                    updated = new_schema;
                }

                if !iteration_changed {
                    break;
                }
            }

            dependency_map.insert(name.clone(), deps);
            processed_map.insert(name.clone(), updated.clone());
            processed.push((name, updated));
        }

        let mut schema_map: HashMap<String, String> = processed.iter().cloned().collect();
        let total = schema_map.len();
        let names: Vec<String> = processed.iter().map(|(name, _)| name.clone()).collect();
        let order_index: HashMap<String, usize> = names
            .iter()
            .enumerate()
            .map(|(idx, name)| (name.clone(), idx))
            .collect();

        let mut indegree: HashMap<String, usize> =
            names.iter().map(|name| (name.clone(), 0_usize)).collect();
        let mut adjacency: HashMap<String, Vec<String>> = HashMap::new();

        for (name, deps) in &dependency_map {
            for dep in deps {
                adjacency.entry(dep.clone()).or_default().push(name.clone());
                *indegree.entry(name.clone()).or_default() += 1;
            }
        }

        let mut ready: BinaryHeap<Reverse<(usize, String)>> = BinaryHeap::new();
        for (name, &deg) in &indegree {
            if deg == 0 {
                let idx = *order_index.get(name).unwrap_or(&usize::MAX);
                ready.push(Reverse((idx, name.clone())));
            }
        }
        let mut ordered = Vec::with_capacity(total);

        while let Some(Reverse((_, name))) = ready.pop() {
            if let Some(schema) = schema_map.remove(&name) {
                ordered.push((name.clone(), schema));
            }

            if let Some(children) = adjacency.remove(&name) {
                for child in children {
                    if let Some(deg) = indegree.get_mut(&child) {
                        if *deg > 0 {
                            *deg -= 1;
                            if *deg == 0 {
                                let idx = *order_index.get(&child).unwrap_or(&usize::MAX);
                                ready.push(Reverse((idx, child.clone())));
                            }
                        }
                    }
                }
            }

            indegree.remove(&name);
        }

        if !schema_map.is_empty() {
            let mut remaining: Vec<(usize, (String, String))> = schema_map
                .into_iter()
                .map(|(name, schema)| {
                    let idx = *order_index.get(&name).unwrap_or(&usize::MAX);
                    (idx, (name, schema))
                })
                .collect();
            remaining.sort_by_key(|(idx, _)| *idx);
            for (_, pair) in remaining {
                ordered.push(pair);
            }
        }

        let mut output =
            String::from("// Automatically generated by zod_gen\nimport * as z from 'zod';\n\n");

        for (name, schema) in ordered {
            output.push_str(&format!(
                "export const {name}Schema = {schema};\nexport type {name} = z.infer<typeof {name}Schema>;\n\n"
            ));
        }

        output
    }
}

// Implementations for common Rust types
impl ZodSchema for String {
    fn zod_schema() -> String {
        zod_string().to_string()
    }
}

impl ZodSchema for i32 {
    fn zod_schema() -> String {
        zod_number().to_string()
    }
}

impl ZodSchema for i64 {
    fn zod_schema() -> String {
        zod_number().to_string()
    }
}

impl ZodSchema for u32 {
    fn zod_schema() -> String {
        zod_number().to_string()
    }
}

impl ZodSchema for u64 {
    fn zod_schema() -> String {
        zod_number().to_string()
    }
}

impl ZodSchema for f32 {
    fn zod_schema() -> String {
        zod_number().to_string()
    }
}

impl ZodSchema for f64 {
    fn zod_schema() -> String {
        zod_number().to_string()
    }
}

impl ZodSchema for bool {
    fn zod_schema() -> String {
        zod_boolean().to_string()
    }
}

impl<T: ZodSchema> ZodSchema for Option<T> {
    fn zod_schema() -> String {
        zod_nullable(&T::zod_schema())
    }
}

impl<T: ZodSchema> ZodSchema for Vec<T> {
    fn zod_schema() -> String {
        zod_array(&T::zod_schema())
    }
}

impl<T: ZodSchema> ZodSchema for HashMap<String, T> {
    fn zod_schema() -> String {
        zod_record(&T::zod_schema())
    }
}

impl ZodSchema for serde_json::Value {
    fn zod_schema() -> String {
        "z.any()".to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate as zod_gen;
    use serde::{Deserialize, Serialize};
    use serde_json::Value;
    use zod_gen_derive::ZodSchema;

    #[test]
    fn test_primitives() {
        assert_eq!(zod_string(), "z.string()");
        assert_eq!(zod_number(), "z.number()");
        assert_eq!(zod_boolean(), "z.boolean()");
        assert_eq!(zod_bigint(), "z.bigint()");
    }

    #[derive(Debug)]
    struct Dummy;

    impl ZodSchema for Dummy {
        fn zod_schema() -> String {
            zod_string().into()
        }
    }

    #[test]
    fn test_generator() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<Dummy>("Dummy");
        let output = gen.generate();
        assert!(output.contains("DummySchema = z.string()"));
        assert!(output.contains("export type Dummy"));
    }

    #[test]
    fn test_generate_schemas() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<Dummy>("Dummy");
        let output = gen.generate();
        assert!(output.contains("// Automatically generated by zod_gen"));
        assert!(output.contains("import * as z from 'zod';"));
        assert!(output.contains("DummySchema = z.string()"));
    }

    #[test]
    fn test_generic_hashmap() {
        // Test HashMap<String, String>
        assert_eq!(
            <HashMap<String, String>>::zod_schema(),
            "z.record(z.string(), z.string())"
        );

        // Test HashMap<String, i32>
        assert_eq!(
            <HashMap<String, i32>>::zod_schema(),
            "z.record(z.string(), z.number())"
        );

        // Test HashMap<String, Option<bool>>
        assert_eq!(
            <HashMap<String, Option<bool>>>::zod_schema(),
            "z.record(z.string(), z.boolean().nullable())"
        );

        // Test HashMap<String, Vec<String>>
        assert_eq!(
            <HashMap<String, Vec<String>>>::zod_schema(),
            "z.record(z.string(), z.array(z.string()))"
        );
    }

    #[test]
    fn test_zod_object_quotes_invalid_property_name() {
        let schema = zod_object(&[("$semicolon_field;", zod_string())]);
        assert!(schema.contains("\"$semicolon_field;\": z.string()"));
    }

    #[test]
    fn test_zod_enum_handles_special_characters() {
        let schema = zod_enum(&["value-with-hyphen", "$value", "simple"]);
        assert!(schema.contains("z.literal('value-with-hyphen')"));
        assert!(schema.contains("z.literal('$value')"));
        assert!(schema.contains("z.literal('simple')"));
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    struct InnerModel {
        value: String,
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    struct OuterModel {
        inner: InnerModel,
        maybe_inner: Option<InnerModel>,
        list: Vec<InnerModel>,
        registry: HashMap<String, InnerModel>,
    }

    #[test]
    fn test_generator_reuses_nested_struct_schemas() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<InnerModel>("InnerModel");
        gen.add_schema::<OuterModel>("OuterModel");

        let output = gen.generate();
        assert!(output.contains("export const InnerModelSchema ="));
        assert!(output.contains("export const OuterModelSchema ="));
        assert!(output.contains("inner: InnerModelSchema"));
        assert!(output.contains("maybe_inner: InnerModelSchema.nullable()"));
        assert!(output.contains("list: z.array(InnerModelSchema)"));
        assert!(output.contains("registry: z.record(z.string(), InnerModelSchema)"));
        let inline_registry_marker = "registry: z.record(z.string(), z.object({";
        assert!(!output.contains(inline_registry_marker));
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    enum StatusModel {
        Active,
        Inactive,
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    struct StatusContainer {
        status: StatusModel,
        optional_status: Option<StatusModel>,
    }

    #[test]
    fn test_generator_reuses_nested_enum_schemas() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<StatusModel>("StatusModel");
        gen.add_schema::<StatusContainer>("StatusContainer");

        let output = gen.generate();
        assert!(output.contains("export const StatusModelSchema ="));
        assert!(output.contains("export const StatusContainerSchema ="));
        assert!(output.contains("status: StatusModelSchema"));
        assert!(output.contains("optional_status: StatusModelSchema.nullable()"));
        assert!(!output.contains("status: z.union(["));
    }

    #[derive(ZodSchema, Default, Serialize, Deserialize)]
    #[allow(dead_code)]
    #[serde(rename_all = "camelCase")]
    struct NestedChild {
        #[serde(rename = "id64", alias = "id")]
        id: i64,
    }

    #[derive(ZodSchema, Default, Serialize, Deserialize)]
    #[allow(dead_code)]
    #[serde(rename_all = "camelCase")]
    struct NestedParent {
        #[serde(rename = "id64", alias = "id")]
        id: i64,
        children: Vec<NestedChild>,
    }

    #[test]
    fn test_generator_handles_vec_of_nested_structs() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<NestedChild>("NestedChild");
        gen.add_schema::<NestedParent>("NestedParent");

        let output = gen.generate();
        assert!(output.contains("export const NestedChildSchema ="));
        assert!(output.contains("export const NestedParentSchema ="));
        assert!(output.contains("children: z.array(NestedChildSchema)"));
        let child_idx = output
            .find("export const NestedChildSchema")
            .expect("NestedChildSchema should be present");
        let parent_idx = output
            .find("export const NestedParentSchema")
            .expect("NestedParentSchema should be present");
        assert!(
            child_idx < parent_idx,
            "NestedChildSchema should be declared before NestedParentSchema"
        );
    }

    #[derive(ZodSchema, Default, Serialize, Deserialize)]
    #[allow(dead_code)]
    #[serde(rename_all = "camelCase")]
    struct DeepNestedParent {
        #[serde(rename = "id64", alias = "id")]
        id: i64,
        child_matrix: Option<Vec<Vec<NestedChild>>>,
    }

    #[test]
    fn test_generator_handles_deeply_nested_structs() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<NestedChild>("NestedChild");
        gen.add_schema::<DeepNestedParent>("DeepNestedParent");

        let output = gen.generate();
        assert!(output.contains("child_matrix: z.array(z.array(NestedChildSchema)).nullable()"));
        let child_idx = output
            .find("export const NestedChildSchema")
            .expect("NestedChildSchema should be present");
        let parent_idx = output
            .find("export const DeepNestedParentSchema")
            .expect("DeepNestedParentSchema should be present");
        assert!(
            child_idx < parent_idx,
            "NestedChildSchema should be declared before DeepNestedParentSchema"
        );
    }

    #[test]
    fn test_generator_handles_dependency_added_after_parent() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<NestedParent>("Ancestor");
        gen.add_schema::<NestedChild>("ZetaChild");

        let output = gen.generate();
        let parent_idx = output
            .find("export const AncestorSchema")
            .expect("AncestorSchema should be present");
        let child_idx = output
            .find("export const ZetaChildSchema")
            .expect("ZetaChildSchema should be present");
        assert!(
            child_idx < parent_idx,
            "ZetaChildSchema should be declared before AncestorSchema even when added later"
        );
        assert!(output.contains("children: z.array(ZetaChildSchema)"));
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    struct SchemaFoo {
        value: String,
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    struct SchemaBar {
        flag: bool,
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    struct SchemaBaz {
        data: i32,
    }

    #[derive(ZodSchema, Serialize, Deserialize)]
    #[allow(dead_code)]
    struct SameShapeA {
        value: bool,
    }

    #[derive(ZodSchema, Serialize, Deserialize)]
    #[allow(dead_code)]
    struct SameShapeB {
        value: bool,
    }

    #[derive(ZodSchema, Serialize, Deserialize)]
    #[allow(dead_code)]
    struct SameShapeParent {
        child: SameShapeB,
    }

    #[test]
    fn test_generator_prefers_actual_dependency_when_shapes_match() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<SameShapeA>("SameShapeA");
        gen.add_schema::<SameShapeB>("SameShapeB");
        gen.add_schema::<SameShapeParent>("SameShapeParent");

        let output = gen.generate();
        assert!(output.contains("export const SameShapeASchema"));
        assert!(output.contains("export const SameShapeBSchema"));
        assert!(output.contains("child: z.object({"));
        assert!(!output.contains("child: SameShapeASchema"));
        assert!(!output.contains("child: SameShapeBSchema"));
    }

    #[derive(ZodSchema, Default, Serialize, Deserialize)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct DomainLandingPads {
        large: i32,
        medium: i32,
        small: i32,
    }

    #[derive(ZodSchema, Default, Serialize, Deserialize)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct DomainMarket {
        commodities: Vec<String>,
        update_time: String,
    }

    #[derive(ZodSchema, Default, Serialize, Deserialize)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct DomainStation {
        name: String,
        #[serde(rename = "type")]
        station_type: Option<String>,
        landing_pads: Option<DomainLandingPads>,
        market: Option<DomainMarket>,
    }

    #[derive(ZodSchema, Default, Serialize, Deserialize)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct DomainBody {
        name: String,
        stations: Vec<DomainStation>,
        update_time: String,
    }

    #[derive(ZodSchema, Default, Serialize, Deserialize)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct DomainStarSystem {
        bodies: Vec<DomainBody>,
        stations: Vec<DomainStation>,
    }

    #[test]
    fn test_generator_handles_complex_domain_structures_without_inlining() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<DomainLandingPads>("DomainLandingPads");
        gen.add_schema::<DomainMarket>("DomainMarket");
        gen.add_schema::<DomainStation>("DomainStation");
        gen.add_schema::<DomainBody>("DomainBody");
        gen.add_schema::<DomainStarSystem>("DomainStarSystem");

        let output = gen.generate();
        assert!(output.contains("landing_pads: DomainLandingPadsSchema.nullable()"));
        assert!(output.contains("market: DomainMarketSchema.nullable()"));
        assert!(output.contains("stations: z.array(DomainStationSchema)"));
        assert!(output.contains("bodies: z.array(DomainBodySchema)"));
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeBelt {
        name: String,
        #[serde(rename = "type")]
        belt_type: String,
        mass: f64,
        inner_radius: f64,
        outer_radius: f64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeCoords {
        x: f64,
        y: f64,
        z: f64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeControllingFaction {
        name: String,
        government: Option<String>,
        allegiance: Option<String>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeFaction {
        name: String,
        allegiance: String,
        government: String,
        influence: f64,
        state: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeLandingPads {
        large: i32,
        medium: i32,
        small: i32,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeCommodity {
        name: String,
        symbol: String,
        category: String,
        commodity_id: i32,
        demand: i32,
        supply: i32,
        buy_price: i32,
        sell_price: i32,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeMarket {
        #[serde(default)]
        commodities: Vec<LargeCommodity>,
        #[serde(default)]
        prohibited_commodities: Vec<String>,
        update_time: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeModule {
        name: String,
        symbol: String,
        module_id: i32,
        #[serde(rename = "class")]
        class_grade: i32,
        rating: String,
        category: String,
        ship: Option<String>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeOutfitting {
        #[serde(default)]
        modules: Vec<LargeModule>,
        update_time: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeShip {
        name: String,
        symbol: String,
        ship_id: i32,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeShipyard {
        #[serde(default)]
        ships: Vec<LargeShip>,
        update_time: String,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default)]
    struct LargeSignalsInternal {
        #[serde(rename = "$SAA_SignalType_Human;")]
        saa_signal_type_human: i32,
        #[serde(rename = "$SAA_SignalType_Other;")]
        saa_signal_type_other: Option<i32>,
        #[serde(rename = "$SAA_SignalType_Geological;")]
        saa_signal_type_geological: Option<i32>,
        #[serde(rename = "SAA_SignalType_Biological;")]
        saa_signal_type_biological: Option<i32>,
        opal: i32,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeSignals {
        #[serde(default, rename = "signals")]
        signals_internal: LargeSignalsInternal,
        #[serde(default)]
        genuses: Vec<Value>,
        update_time: Option<String>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeRingSignals {
        #[serde(default)]
        signals: HashMap<String, Value>,
        update_time: Option<String>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeRing {
        name: String,
        #[serde(rename = "type")]
        ring_type: String,
        mass: f64,
        inner_radius: f64,
        outer_radius: f64,
        #[serde(rename = "id64", alias = "id")]
        id: i64,
        signals: Option<LargeRingSignals>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeSolidComposition {
        ice: f64,
        metal: f64,
        rock: f64,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeStation {
        name: String,
        id: i64,
        update_time: String,
        controlling_faction: Option<String>,
        controlling_faction_state: Option<String>,
        distance_to_arrival: f64,
        primary_economy: Option<String>,
        #[serde(default)]
        economies: HashMap<String, f64>,
        allegiance: Option<String>,
        government: Option<String>,
        #[serde(default)]
        services: Vec<String>,
        #[serde(rename = "type")]
        station_type: Option<String>,
        state: Option<String>,
        latitude: f64,
        longitude: f64,
        landing_pads: Option<LargeLandingPads>,
        market: Option<LargeMarket>,
        shipyard: Option<LargeShipyard>,
        outfitting: Option<LargeOutfitting>,
    }

    #[derive(Debug, Clone, PartialEq, Serialize, Deserialize, ZodSchema, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeBody {
        #[serde(rename = "id64", alias = "id")]
        id: i64,
        body_id: i32,
        name: Option<String>,
        #[serde(rename = "type")]
        body_type: Option<String>,
        sub_type: Option<String>,
        distance_to_arrival: f64,
        main_star: bool,
        age: i32,
        spectral_class: Option<String>,
        luminosity: Option<String>,
        absolute_magnitude: f64,
        solar_masses: f64,
        solar_radius: f64,
        surface_temperature: f64,
        rotational_period: f64,
        axial_tilt: f64,
        #[serde(default)]
        belts: Vec<LargeBelt>,
        #[serde(default)]
        timestamps: HashMap<String, String>,
        #[serde(default)]
        stations: Vec<LargeStation>,
        update_time: String,
        is_landable: bool,
        gravity: f64,
        earth_masses: f64,
        radius: f64,
        surface_pressure: f64,
        atmosphere_type: Option<String>,
        solid_composition: Option<LargeSolidComposition>,
        terraforming_state: Option<String>,
        materials: Option<HashMap<String, f64>>,
        signals: Option<LargeSignals>,
        rotational_period_tidally_locked: Option<bool>,
        #[serde(default)]
        parents: Vec<HashMap<String, i64>>,
        orbital_period: f64,
        semi_major_axis: f64,
        orbital_eccentricity: f64,
        orbital_inclination: f64,
        arg_of_periapsis: f64,
        mean_anomaly: f64,
        ascending_node: f64,
        volcanism_type: Option<String>,
        #[serde(default)]
        atmosphere_composition: HashMap<String, f64>,
        reserve_level: Option<String>,
        #[serde(default)]
        rings: Vec<LargeRing>,
    }

    #[derive(ZodSchema, Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
    #[allow(dead_code)]
    #[serde(default, rename_all = "camelCase")]
    struct LargeStarSystem {
        #[serde(rename = "id64", alias = "id")]
        id: i64,
        name: String,
        coords: LargeCoords,
        allegiance: Option<String>,
        government: Option<String>,
        primary_economy: Option<String>,
        secondary_economy: Option<String>,
        security: Option<String>,
        population: i64,
        body_count: i32,
        controlling_faction: Option<LargeControllingFaction>,
        #[serde(default)]
        factions: Vec<LargeFaction>,
        controlling_power: Option<String>,
        power_state: Option<String>,
        power_state_control_progress: f64,
        power_state_reinforcement: i32,
        power_state_undermining: i32,
        #[serde(default)]
        powers: Vec<String>,
        #[serde(default)]
        timestamps: HashMap<String, String>,
        date: Option<String>,
        #[serde(default)]
        bodies: Vec<LargeBody>,
        #[serde(default)]
        stations: Vec<LargeStation>,
    }

    #[test]
    fn test_generator_handles_large_realistic_structure() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<LargeLandingPads>("LandingPads");
        gen.add_schema::<LargeCommodity>("Commodity");
        gen.add_schema::<LargeMarket>("Market");
        gen.add_schema::<LargeModule>("Module");
        gen.add_schema::<LargeOutfitting>("Outfitting");
        gen.add_schema::<LargeShip>("Ship");
        gen.add_schema::<LargeShipyard>("Shipyard");
        gen.add_schema::<LargeSignalsInternal>("SignalsInternal");
        gen.add_schema::<LargeSignals>("Signals");
        gen.add_schema::<LargeRingSignals>("RingSignals");
        gen.add_schema::<LargeRing>("Ring");
        gen.add_schema::<LargeSolidComposition>("SolidComposition");
        gen.add_schema::<LargeBelt>("Belt");
        gen.add_schema::<LargeStation>("Station");
        gen.add_schema::<LargeBody>("Body");
        gen.add_schema::<LargeCoords>("Coords");
        gen.add_schema::<LargeControllingFaction>("ControllingFaction");
        gen.add_schema::<LargeFaction>("Faction");
        gen.add_schema::<LargeStarSystem>("StarSystem");

        let output = gen.generate();
        let station_refs = output.matches("stations: z.array(StationSchema)").count();
        assert!(
            station_refs >= 2,
            "expected Body and StarSystem to reuse StationSchema"
        );
        assert!(output.contains("landing_pads: LandingPadsSchema.nullable()"));
        assert!(output.contains("market: MarketSchema.nullable()"));
        assert!(output.contains("shipyard: ShipyardSchema.nullable()"));
        assert!(output.contains("outfitting: OutfittingSchema.nullable()"));
        assert!(output.contains("bodies: z.array(BodySchema)"));
    }

    #[test]
    fn test_generator_preserves_insertion_order_for_independent_schemas() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<SchemaBaz>("SchemaBaz");
        gen.add_schema::<SchemaFoo>("SchemaFoo");
        gen.add_schema::<SchemaBar>("SchemaBar");

        let output = gen.generate();
        let baz_idx = output.find("export const SchemaBazSchema").unwrap();
        let foo_idx = output.find("export const SchemaFooSchema").unwrap();
        let bar_idx = output.find("export const SchemaBarSchema").unwrap();

        assert!(
            baz_idx < foo_idx,
            "SchemaBaz should appear before SchemaFoo"
        );
        assert!(
            foo_idx < bar_idx,
            "SchemaFoo should appear before SchemaBar"
        );
    }
}
