//! # Zod Schema Generation for Rust Types
//!
//! Generate [Zod](https://zod.dev) schemas and TypeScript types from Rust types with full serde rename support.
//!
//! ## Quick Start with Derive Macro (Recommended)
//!
//! ```rust,ignore
//! use zod_gen::{ZodSchema, ZodGenerator};
//! use zod_gen_derive::ZodSchema;
//! use serde::{Serialize, Deserialize};
//!
//! #[derive(ZodSchema, Serialize, Deserialize)]
//! struct User {
//!     id: u32,
//!     name: String,
//!     email: Option<String>,
//! }
//!
//! #[derive(ZodSchema, Serialize, Deserialize)]
//! enum Status {
//!     #[serde(rename = "active")]
//!     Active,
//!     #[serde(rename = "inactive")]
//!     Inactive,
//! }
//!
//! let mut generator = ZodGenerator::new();
//! generator.add_schema::<User>("User");
//! generator.add_schema::<Status>("Status");
//!
//! let typescript = generator.generate();
//! // typescript contains the generated Zod schemas
//! ```
//!
//! This generates:
//!
//! ```typescript
//! // Automatically generated by zod_gen
//! import * as z from 'zod';
//!
//! export const UserSchema = z.object({
//!   id: z.number(),
//!   name: z.string(),
//!   email: z.string().nullable()
//! });
//! export type User = z.infer<typeof UserSchema>;
//!
//! export const StatusSchema = z.union([z.literal("active"), z.literal("inactive")]);
//! export type Status = z.infer<typeof StatusSchema>;
//! ```
//!
//! ## Manual Implementation
//!
//! For custom schema generation, implement the `ZodSchema` trait manually:
//!
//! ```rust
//! use zod_gen::{ZodSchema, zod_object, zod_string};
//!
//! struct CustomType {
//!     field: String,
//! }
//!
//! impl ZodSchema for CustomType {
//!     fn zod_schema() -> String {
//!         zod_object(&[("field", zod_string())])
//!     }
//! }
//! ```
//!
//! ## Features
//!
//! - **Derive Macro**: Automatic schema generation with `#[derive(ZodSchema)]`
//! - **Serde Rename Support**: Full support for `#[serde(rename = "...")]` attributes
//! - **Type Safety**: Generated TypeScript types match your Rust types exactly
//! - **Generic Types**: Built-in support for `Option<T>`, `Vec<T>`, `HashMap<String, T>`
//! - **Batch Generation**: Generate multiple schemas in a single TypeScript file
//!
//! ## Installation
//!
//! Add both crates to your `Cargo.toml`:
//!
//! ```toml
//! [dependencies]
//! zod_gen = "1.1.7"
//! zod_gen_derive = "1.1.7"
//! serde = { version = "1.0", features = ["derive"] }
//! ```

use std::{
    cmp::Reverse,
    collections::{BinaryHeap, HashMap},
    fmt::Write,
};

/// Trait for Rust types that can produce a Zod schema
pub trait ZodSchema {
    /// Returns the Zod schema as a string
    fn zod_schema() -> String;
}

/// Helper functions for building Zod schema strings
pub fn zod_string() -> &'static str {
    "z.string()"
}
pub fn zod_number() -> &'static str {
    "z.number()"
}
pub fn zod_bigint() -> &'static str {
    "z.bigint()"
}
pub fn zod_boolean() -> &'static str {
    "z.boolean()"
}

pub fn zod_nullable(inner: &str) -> String {
    format!("{inner}.nullable()")
}
pub fn zod_array(inner: &str) -> String {
    format!("z.array({inner})")
}
pub fn zod_record(value: &str) -> String {
    format!("z.record(z.string(), {value})")
}

fn is_ts_identifier_start(ch: char) -> bool {
    ch == '_' || ch == '$' || ch.is_ascii_alphabetic()
}

fn is_ts_identifier_part(ch: char) -> bool {
    ch == '_' || ch == '$' || ch.is_ascii_alphanumeric()
}

fn is_valid_ts_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(ch) if is_ts_identifier_start(ch) => {
            for ch in chars {
                if !is_ts_identifier_part(ch) {
                    return false;
                }
            }
            true
        }
        _ => false,
    }
}

fn ts_quoted_literal(value: &str, quote: char) -> String {
    let mut escaped = String::with_capacity(value.len() + 2);
    escaped.push(quote);
    for ch in value.chars() {
        match ch {
            '"' if quote == '"' => escaped.push_str("\\\""),
            '\'' if quote == '\'' => escaped.push_str("\\'"),
            '\\' => escaped.push_str("\\\\"),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            '\u{08}' => escaped.push_str("\\b"),
            '\u{0C}' => escaped.push_str("\\f"),
            '\u{2028}' => escaped.push_str("\\u2028"),
            '\u{2029}' => escaped.push_str("\\u2029"),
            ch if ch.is_control() => {
                let _ = write!(escaped, "\\u{:04X}", ch as u32);
            }
            _ => escaped.push(ch),
        }
    }
    escaped.push(quote);
    escaped
}

fn ts_double_quoted_literal(value: &str) -> String {
    ts_quoted_literal(value, '"')
}

fn ts_single_quoted_literal(value: &str) -> String {
    ts_quoted_literal(value, '\'')
}

fn format_ts_property_key(name: &str) -> String {
    if is_valid_ts_identifier(name) {
        name.to_string()
    } else {
        ts_double_quoted_literal(name)
    }
}

fn prev_non_whitespace(s: &str, idx: usize) -> Option<char> {
    s[..idx].chars().rev().find(|c| !c.is_whitespace())
}

fn next_non_whitespace(s: &str, idx: usize) -> Option<char> {
    s[idx..].chars().find(|c| !c.is_whitespace())
}

fn is_valid_reference_context(prev: Option<char>, next: Option<char>) -> bool {
    if prev.is_none() && next.is_none() {
        return false;
    }

    let prev_ok = match prev {
        None => true,
        Some(ch) => matches!(ch, ':' | '(' | '[' | ',' | '='),
    };

    let next_ok = match next {
        None => true,
        Some(ch) => matches!(ch, ')' | ',' | ']' | '}' | '.'),
    };

    prev_ok && next_ok
}

fn replace_schema_refs(schema: String, target: &str, replacement_name: &str) -> (String, bool) {
    if !schema.contains(target) {
        return (schema, false);
    }

    let source = schema;
    let mut result = String::with_capacity(source.len());
    let replacement = format!("{replacement_name}Schema");
    let mut replaced = false;

    {
        let bytes = source.as_str();
        let mut last = 0;

        while let Some(pos) = bytes[last..].find(target) {
            let start = last + pos;
            let end = start + target.len();

            let prev = prev_non_whitespace(bytes, start);
            let next = next_non_whitespace(bytes, end);

            if is_valid_reference_context(prev, next) {
                result.push_str(&bytes[last..start]);
                result.push_str(&replacement);
                last = end;
                replaced = true;
            } else {
                result.push_str(&bytes[last..start + 1]);
                last = start + 1;
            }
        }

        result.push_str(&bytes[last..]);
    }

    if replaced {
        (result, true)
    } else {
        (source, false)
    }
}

pub fn zod_object(fields: &[(&str, &str)]) -> String {
    let items: Vec<String> = fields
        .iter()
        .map(|(k, v)| format!("  {}: {v}", format_ts_property_key(k)))
        .collect();
    format!("z.object({{\n{}\n}})", items.join(",\n"))
}

pub fn zod_enum(variants: &[&str]) -> String {
    let lits: Vec<String> = variants
        .iter()
        .map(|v| format!("z.literal({})", ts_single_quoted_literal(v)))
        .collect();
    format!("z.union([{}])", lits.join(", "))
}

/// Generator that collects schemas and writes TypeScript files
///
/// The `ZodGenerator` generates Zod schemas with proper serde rename support
/// from Rust types, providing TypeScript type safety.
pub struct ZodGenerator {
    schemas: Vec<(String, String)>,
}

impl Default for ZodGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl ZodGenerator {
    pub fn new() -> Self {
        Self {
            schemas: Vec::new(),
        }
    }

    /// Add a Zod schema for a Rust type
    pub fn add_schema<T: ZodSchema>(&mut self, name: &str) {
        let schema = T::zod_schema();
        let name = name.to_string();
        if let Some(existing) = self.schemas.iter_mut().find(|(n, _)| *n == name) {
            existing.1 = schema;
        } else {
            self.schemas.push((name, schema));
        }
    }

    /// Generate Zod schemas file
    ///
    /// Creates a TypeScript file with Zod schemas and inferred types.
    pub fn generate(&self) -> String {
        let entries: Vec<(String, String)> = self.schemas.clone();
        let originals = entries.clone();
        let mut schema_occurrences: HashMap<String, usize> = HashMap::new();
        for (_, schema) in &originals {
            *schema_occurrences.entry(schema.clone()).or_insert(0) += 1;
        }

        let mut processed: Vec<(String, String)> = Vec::with_capacity(entries.len());
        let mut dependency_map: HashMap<String, Vec<String>> = HashMap::new();

        for (name, schema) in entries.into_iter() {
            let mut updated = schema;
            let mut deps = Vec::new();

            for (dep_name, dep_schema) in &originals {
                if dep_name == &name {
                    continue;
                }
                if schema_occurrences
                    .get(dep_schema.as_str())
                    .copied()
                    .unwrap_or(0)
                    > 1
                {
                    continue;
                }
                let (new_schema, replaced) = replace_schema_refs(updated, dep_schema, dep_name);
                if replaced {
                    deps.push(dep_name.clone());
                }
                updated = new_schema;
            }

            dependency_map.insert(name.clone(), deps);
            processed.push((name, updated));
        }

        let mut schema_map: HashMap<String, String> = processed.iter().cloned().collect();
        let total = schema_map.len();
        let names: Vec<String> = processed.iter().map(|(name, _)| name.clone()).collect();
        let order_index: HashMap<String, usize> = names
            .iter()
            .enumerate()
            .map(|(idx, name)| (name.clone(), idx))
            .collect();

        let mut indegree: HashMap<String, usize> =
            names.iter().map(|name| (name.clone(), 0_usize)).collect();
        let mut adjacency: HashMap<String, Vec<String>> = HashMap::new();

        for (name, deps) in &dependency_map {
            for dep in deps {
                adjacency.entry(dep.clone()).or_default().push(name.clone());
                *indegree.entry(name.clone()).or_default() += 1;
            }
        }

        let mut ready: BinaryHeap<Reverse<(usize, String)>> = BinaryHeap::new();
        for (name, &deg) in &indegree {
            if deg == 0 {
                let idx = *order_index.get(name).unwrap_or(&usize::MAX);
                ready.push(Reverse((idx, name.clone())));
            }
        }
        let mut ordered = Vec::with_capacity(total);

        while let Some(Reverse((_, name))) = ready.pop() {
            if let Some(schema) = schema_map.remove(&name) {
                ordered.push((name.clone(), schema));
            }

            if let Some(children) = adjacency.remove(&name) {
                for child in children {
                    if let Some(deg) = indegree.get_mut(&child) {
                        if *deg > 0 {
                            *deg -= 1;
                            if *deg == 0 {
                                let idx = *order_index.get(&child).unwrap_or(&usize::MAX);
                                ready.push(Reverse((idx, child.clone())));
                            }
                        }
                    }
                }
            }

            indegree.remove(&name);
        }

        if !schema_map.is_empty() {
            let mut remaining: Vec<(usize, (String, String))> = schema_map
                .into_iter()
                .map(|(name, schema)| {
                    let idx = *order_index.get(&name).unwrap_or(&usize::MAX);
                    (idx, (name, schema))
                })
                .collect();
            remaining.sort_by_key(|(idx, _)| *idx);
            for (_, pair) in remaining {
                ordered.push(pair);
            }
        }

        let mut output =
            String::from("// Automatically generated by zod_gen\nimport * as z from 'zod';\n\n");

        for (name, schema) in ordered {
            output.push_str(&format!(
                "export const {name}Schema = {schema};\nexport type {name} = z.infer<typeof {name}Schema>;\n\n"
            ));
        }

        output
    }
}

// Implementations for common Rust types
impl ZodSchema for String {
    fn zod_schema() -> String {
        zod_string().to_string()
    }
}

impl ZodSchema for i32 {
    fn zod_schema() -> String {
        zod_number().to_string()
    }
}

impl ZodSchema for i64 {
    fn zod_schema() -> String {
        zod_number().to_string()
    }
}

impl ZodSchema for u32 {
    fn zod_schema() -> String {
        zod_number().to_string()
    }
}

impl ZodSchema for u64 {
    fn zod_schema() -> String {
        zod_number().to_string()
    }
}

impl ZodSchema for f32 {
    fn zod_schema() -> String {
        zod_number().to_string()
    }
}

impl ZodSchema for f64 {
    fn zod_schema() -> String {
        zod_number().to_string()
    }
}

impl ZodSchema for bool {
    fn zod_schema() -> String {
        zod_boolean().to_string()
    }
}

impl<T: ZodSchema> ZodSchema for Option<T> {
    fn zod_schema() -> String {
        zod_nullable(&T::zod_schema())
    }
}

impl<T: ZodSchema> ZodSchema for Vec<T> {
    fn zod_schema() -> String {
        zod_array(&T::zod_schema())
    }
}

impl<T: ZodSchema> ZodSchema for HashMap<String, T> {
    fn zod_schema() -> String {
        zod_record(&T::zod_schema())
    }
}

impl ZodSchema for serde_json::Value {
    fn zod_schema() -> String {
        "z.any()".to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate as zod_gen;
    use serde::{Deserialize, Serialize};
    use zod_gen_derive::ZodSchema;

    #[test]
    fn test_primitives() {
        assert_eq!(zod_string(), "z.string()");
        assert_eq!(zod_number(), "z.number()");
        assert_eq!(zod_boolean(), "z.boolean()");
        assert_eq!(zod_bigint(), "z.bigint()");
    }

    #[derive(Debug)]
    struct Dummy;

    impl ZodSchema for Dummy {
        fn zod_schema() -> String {
            zod_string().into()
        }
    }

    #[test]
    fn test_generator() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<Dummy>("Dummy");
        let output = gen.generate();
        assert!(output.contains("DummySchema = z.string()"));
        assert!(output.contains("export type Dummy"));
    }

    #[test]
    fn test_generate_schemas() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<Dummy>("Dummy");
        let output = gen.generate();
        assert!(output.contains("// Automatically generated by zod_gen"));
        assert!(output.contains("import * as z from 'zod';"));
        assert!(output.contains("DummySchema = z.string()"));
    }

    #[test]
    fn test_generic_hashmap() {
        // Test HashMap<String, String>
        assert_eq!(
            <HashMap<String, String>>::zod_schema(),
            "z.record(z.string(), z.string())"
        );

        // Test HashMap<String, i32>
        assert_eq!(
            <HashMap<String, i32>>::zod_schema(),
            "z.record(z.string(), z.number())"
        );

        // Test HashMap<String, Option<bool>>
        assert_eq!(
            <HashMap<String, Option<bool>>>::zod_schema(),
            "z.record(z.string(), z.boolean().nullable())"
        );

        // Test HashMap<String, Vec<String>>
        assert_eq!(
            <HashMap<String, Vec<String>>>::zod_schema(),
            "z.record(z.string(), z.array(z.string()))"
        );
    }

    #[test]
    fn test_zod_object_quotes_invalid_property_name() {
        let schema = zod_object(&[("$semicolon_field;", zod_string())]);
        assert!(schema.contains("\"$semicolon_field;\": z.string()"));
    }

    #[test]
    fn test_zod_enum_handles_special_characters() {
        let schema = zod_enum(&["value-with-hyphen", "$value", "simple"]);
        assert!(schema.contains("z.literal('value-with-hyphen')"));
        assert!(schema.contains("z.literal('$value')"));
        assert!(schema.contains("z.literal('simple')"));
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    struct InnerModel {
        value: String,
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    struct OuterModel {
        inner: InnerModel,
        maybe_inner: Option<InnerModel>,
        list: Vec<InnerModel>,
        registry: HashMap<String, InnerModel>,
    }

    #[test]
    fn test_generator_reuses_nested_struct_schemas() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<InnerModel>("InnerModel");
        gen.add_schema::<OuterModel>("OuterModel");

        let output = gen.generate();
        assert!(output.contains("export const InnerModelSchema ="));
        assert!(output.contains("export const OuterModelSchema ="));
        assert!(output.contains("inner: InnerModelSchema"));
        assert!(output.contains("maybe_inner: InnerModelSchema.nullable()"));
        assert!(output.contains("list: z.array(InnerModelSchema)"));
        assert!(output.contains("registry: z.record(z.string(), InnerModelSchema)"));
        let inline_registry_marker = "registry: z.record(z.string(), z.object({";
        assert!(!output.contains(inline_registry_marker));
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    enum StatusModel {
        Active,
        Inactive,
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    struct StatusContainer {
        status: StatusModel,
        optional_status: Option<StatusModel>,
    }

    #[test]
    fn test_generator_reuses_nested_enum_schemas() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<StatusModel>("StatusModel");
        gen.add_schema::<StatusContainer>("StatusContainer");

        let output = gen.generate();
        assert!(output.contains("export const StatusModelSchema ="));
        assert!(output.contains("export const StatusContainerSchema ="));
        assert!(output.contains("status: StatusModelSchema"));
        assert!(output.contains("optional_status: StatusModelSchema.nullable()"));
        assert!(!output.contains("status: z.union(["));
    }

    #[derive(ZodSchema, Default, Serialize, Deserialize)]
    #[allow(dead_code)]
    #[serde(rename_all = "camelCase")]
    struct NestedChild {
        #[serde(rename = "id64", alias = "id")]
        id: i64,
    }

    #[derive(ZodSchema, Default, Serialize, Deserialize)]
    #[allow(dead_code)]
    #[serde(rename_all = "camelCase")]
    struct NestedParent {
        #[serde(rename = "id64", alias = "id")]
        id: i64,
        children: Vec<NestedChild>,
    }

    #[test]
    fn test_generator_handles_vec_of_nested_structs() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<NestedChild>("NestedChild");
        gen.add_schema::<NestedParent>("NestedParent");

        let output = gen.generate();
        assert!(output.contains("export const NestedChildSchema ="));
        assert!(output.contains("export const NestedParentSchema ="));
        assert!(output.contains("children: z.array(NestedChildSchema)"));
        let child_idx = output
            .find("export const NestedChildSchema")
            .expect("NestedChildSchema should be present");
        let parent_idx = output
            .find("export const NestedParentSchema")
            .expect("NestedParentSchema should be present");
        assert!(
            child_idx < parent_idx,
            "NestedChildSchema should be declared before NestedParentSchema"
        );
    }

    #[derive(ZodSchema, Default, Serialize, Deserialize)]
    #[allow(dead_code)]
    #[serde(rename_all = "camelCase")]
    struct DeepNestedParent {
        #[serde(rename = "id64", alias = "id")]
        id: i64,
        child_matrix: Option<Vec<Vec<NestedChild>>>,
    }

    #[test]
    fn test_generator_handles_deeply_nested_structs() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<NestedChild>("NestedChild");
        gen.add_schema::<DeepNestedParent>("DeepNestedParent");

        let output = gen.generate();
        assert!(output.contains("child_matrix: z.array(z.array(NestedChildSchema)).nullable()"));
        let child_idx = output
            .find("export const NestedChildSchema")
            .expect("NestedChildSchema should be present");
        let parent_idx = output
            .find("export const DeepNestedParentSchema")
            .expect("DeepNestedParentSchema should be present");
        assert!(
            child_idx < parent_idx,
            "NestedChildSchema should be declared before DeepNestedParentSchema"
        );
    }

    #[test]
    fn test_generator_handles_dependency_added_after_parent() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<NestedParent>("Ancestor");
        gen.add_schema::<NestedChild>("ZetaChild");

        let output = gen.generate();
        let parent_idx = output
            .find("export const AncestorSchema")
            .expect("AncestorSchema should be present");
        let child_idx = output
            .find("export const ZetaChildSchema")
            .expect("ZetaChildSchema should be present");
        assert!(
            child_idx < parent_idx,
            "ZetaChildSchema should be declared before AncestorSchema even when added later"
        );
        assert!(output.contains("children: z.array(ZetaChildSchema)"));
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    struct SchemaFoo {
        value: String,
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    struct SchemaBar {
        flag: bool,
    }

    #[derive(ZodSchema)]
    #[allow(dead_code)]
    struct SchemaBaz {
        data: i32,
    }

    #[derive(ZodSchema, Serialize, Deserialize)]
    #[allow(dead_code)]
    struct SameShapeA {
        value: bool,
    }

    #[derive(ZodSchema, Serialize, Deserialize)]
    #[allow(dead_code)]
    struct SameShapeB {
        value: bool,
    }

    #[derive(ZodSchema, Serialize, Deserialize)]
    #[allow(dead_code)]
    struct SameShapeParent {
        child: SameShapeB,
    }

    #[test]
    fn test_generator_prefers_actual_dependency_when_shapes_match() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<SameShapeA>("SameShapeA");
        gen.add_schema::<SameShapeB>("SameShapeB");
        gen.add_schema::<SameShapeParent>("SameShapeParent");

        let output = gen.generate();
        assert!(output.contains("export const SameShapeASchema"));
        assert!(output.contains("export const SameShapeBSchema"));
        assert!(output.contains("child: z.object({"));
        assert!(!output.contains("child: SameShapeASchema"));
        assert!(!output.contains("child: SameShapeBSchema"));
    }

    #[test]
    fn test_generator_preserves_insertion_order_for_independent_schemas() {
        let mut gen = ZodGenerator::new();
        gen.add_schema::<SchemaBaz>("SchemaBaz");
        gen.add_schema::<SchemaFoo>("SchemaFoo");
        gen.add_schema::<SchemaBar>("SchemaBar");

        let output = gen.generate();
        let baz_idx = output.find("export const SchemaBazSchema").unwrap();
        let foo_idx = output.find("export const SchemaFooSchema").unwrap();
        let bar_idx = output.find("export const SchemaBarSchema").unwrap();

        assert!(
            baz_idx < foo_idx,
            "SchemaBaz should appear before SchemaFoo"
        );
        assert!(
            foo_idx < bar_idx,
            "SchemaFoo should appear before SchemaBar"
        );
    }
}
